chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.index, name='index'),
    path('chat-room/<str:room_name>/', views.room, name='room'),
    path('room/', views.room_id, name='room_id'),
    path('<int:pk>/', views.get_id, name='get_id'),
    path('create_room/', views.create_room, name='create_room'),
    path('addusers/<int:pk>/', views.add_users, name='add_users'),
    path('room/<int:pk>/', views.room_rel, name='room_rel'),
    path('change-setting/', views.changeSettings, name='change'),
    path('remove-user/<int:pk>/', views.remove_user, name='remove'),
]

mysite/urls.py
from django.conf.urls import include
from django.urls import path
from django.contrib import admin
from login.views import user_login, user_logout, register, index


urlpatterns = [
    path('', index, name='index'),
    path('chat/', include('chat.urls')),
    path('admin/', admin.site.urls),
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('register/', register, name='register'),
]

chat/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid


class UserList(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    display_name = models.CharField(max_length=100)
    userlist_id = models.CharField(default=uuid.uuid4, max_length=100)

    def __str__(self):
        return str(self.user)


class RoomChat(models.Model):
    new_message = models.BooleanField(default=False)
    name = models.CharField(max_length=20, unique=False)
    admin = models.ForeignKey(
        User, on_delete=models.CASCADE, blank=True, null=True)
    room_id = models.CharField(default=uuid.uuid4, max_length=100)

    def __str__(self):
        return self.name


class AddUser(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(RoomChat, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user} - {self.room}'


class Chat(models.Model):
    userlist_id1 = models.CharField(max_length=100)
    userlist_id2 = models.CharField(max_length=100)
    chat_id = models.CharField(default=uuid.uuid4, max_length=100)
    new_message = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.chat_id}'


class Messages(models.Model):
    private_chat = models.ForeignKey(
        Chat, models.CASCADE, blank=True, null=True)
    room_chat = models.ForeignKey(
        RoomChat, models.CASCADE, blank=True, null=True)
    messages = models.CharField(max_length=200)
    documents = models.FileField(default='documents/')
    user = models.CharField(max_length=200)
    time = models.TimeField(auto_now_add=True)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'{self.user} - {self.messages}'


class Notification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room_chat = models.ForeignKey(
        RoomChat, models.CASCADE, blank=True, null=True, related_name='notification')
    new_message = models.BooleanField(default=False)
    count = models.IntegerField(default=0)


class NotificationPrivate(models.Model):
    sender = models.ForeignKey(
        UserList, on_delete=models.CASCADE,  blank=True, null=True, related_name='notification')
    receiver = models.ForeignKey(
        User, on_delete=models.CASCADE,  blank=True, null=True,)
    # private_chat = models.ForeignKey(
    #     Chat, models.CASCADE, blank=True, null=True)
    new_message = models.BooleanField(default=False)
    count = models.IntegerField(default=0)

chat/views.py
from django.shortcuts import render
from .models import UserList, Chat, Messages, RoomChat, AddUser, Notification, NotificationPrivate
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
import time
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
import json


@login_required(login_url='/login/')
def index(request):
    if request.method == 'GET':
        users = UserList.objects.exclude(user__username=request.user.username)
        rooms = AddUser.objects.filter(user__username=request.user.username)
        return render(request, 'chat/index.html', {'users': users, 'rooms': rooms})


def get_id(request, pk):
    receiver_user = UserList.objects.all().get(id=pk)
    receiver_user_id = receiver_user.userlist_id
    sent_user = UserList.objects.all().get(user=request.user)
    sent_user_id = sent_user.userlist_id
    try:
        chat = Chat.objects.get(userlist_id1=sent_user_id,
                                userlist_id2=receiver_user_id)
        chat_id = chat.chat_id
    except Chat.DoesNotExist:
        try:
            chat = Chat.objects.get(userlist_id2=sent_user_id,
                                    userlist_id1=receiver_user_id)
            chat_id = chat.chat_id
        except Chat.DoesNotExist:
            chat = Chat(userlist_id1=sent_user_id,
                        userlist_id2=receiver_user_id)
            chat.save()
            chat = Chat.objects.get(userlist_id1=sent_user_id,
                                    userlist_id2=receiver_user_id)
            chat_id = chat.chat_id[:7]
            chat.chat_id = chat_id
            chat.save()
    c = chat_id[:7]
    try:
        notify = NotificationPrivate.objects.get(
            receiver=sent_user.user, sender=receiver_user)
        notify.new_message = False
        notify.count = 0
        notify.save()
    except:
        pass
    return HttpResponseRedirect(reverse('chat:room', args=(c,)))


@login_required(login_url='/login/')
def room(request, room_name):
    try:
        opposite_user = Chat.objects.get(chat_id=room_name)
        user = UserList.objects.get(user__username=request.user.username)
        userid = user.userlist_id
        if userid == opposite_user.userlist_id1:
            chat_name = UserList.objects.get(
                userlist_id=opposite_user.userlist_id2)
            chat_name = chat_name.user.username
        else:
            chat_name = UserList.objects.get(
                userlist_id=opposite_user.userlist_id1)
            chat_name = chat_name.user.username
        return render(request, 'chat/room.html', {
            'room_id': room_name,
            'chat_name': chat_name,
            'group': 'private',
        })
    except Chat.DoesNotExist:

        users = AddUser.objects.filter(room__room_id=room_name)
        room = users[0].room.name
        roomId = users[0].room.id
        if request.user == users[0].room.admin:
            admin = True
        else:
            admin = False
        chat_name = room
        return render(request, 'chat/room.html', {
            'room_id': room_name,
            'chat_name': chat_name,
            'group': 'room',
            'users': users,
            'admin': admin,
            'roomId': roomId
        })


@ csrf_exempt
def create_room(request):
    roomName = request.POST.get('room')
    room = RoomChat(name=roomName, admin=request.user)
    room.save()
    new_user = AddUser(user=request.user, room=room)
    new_user.save()
    room = RoomChat.objects.get(id=room.id)
    room_id = room.room_id[:7]
    room.room_id = room_id
    room.save()
    return HttpResponse(json.dumps({'room': room_id}), content_type='application/json')


@ csrf_exempt
def room_id(request):
    roomid = request.POST.get('room')
    room_name = request.POST.get('room_name')
    try:
        notify = Notification.objects.get(
            user=request.user, room_chat__room_id=roomid)
        notify.new_message = False
        notify.count = 0
        notify.save()
    except:
        pass
    room = RoomChat.objects.get(room_id=roomid)
    return HttpResponseRedirect(reverse('chat:room', args=(roomid,)))


def add_users(request, pk):
    added = AddUser.objects.filter(room=pk)
    room = added[0].room
    users = []
    for u in added:
        users.append(User.objects.get(username=u.user.username))
    to_add = UserList.objects.exclude(user__in=users)
    if request.method == 'POST':
        users = request.POST.getlist('users[]')
        for u in users:
            user = UserList.objects.get(id=u)
            add = AddUser(room=room, user=user.user)
            add.save()
        return HttpResponseRedirect(reverse('chat:index'))
    return render(request, 'chat/add_users.html', {'users': to_add})


def changeSettings(request):
    if 'name' in request.GET:
        if request.method == 'POST':
            name = request.POST.get('name')
            name = name.replace(" ", "")

            # Change name in messages
            messages = Messages.objects.filter(user=request.user.username)
            for message in messages:
                message.user = name
                message.save()

            user = UserList.objects.get(user__username=request.user.username)
            user.display_name = name
            user.save()
            user = User.objects.get(username=request.user.username)
            user.username = name
            user.save()

            return HttpResponseRedirect(reverse('index'))
        else:
            messages = Messages.objects.filter(user=request.user.username)
            return render(request, 'chat/change.html', {'change': 'name'})


def room_rel(request, pk):
    room = AddUser.objects.get(id=pk)
    if 'leave_room' in request.GET:
        if request.method == 'POST':
            room.delete()
            return HttpResponseRedirect(reverse('chat:index'))
        return render(request, 'chat/delete_leave.html', {'status': 'leave'})
    if 'delete_room' in request.GET:
        room = room.room
        if request.method == 'POST':
            room.delete()
            return HttpResponseRedirect(reverse('chat:index'))
        return render(request, 'chat/delete_leave.html', {'status': 'delete'})
    if 'change_name' in request.GET:
        room = room.room
        if request.method == 'POST':
            room.name = request.POST.get('change')
            room.save()
            return HttpResponseRedirect(reverse('chat:index'))
        return render(request, 'chat/delete_leave.html', {'status': 'change_name'})


def remove_user(request, pk):
    user = AddUser.objects.get(id=pk)
    room = user.room.room_id
    if request.method == 'POST':
        user.delete()
        return HttpResponseRedirect(reverse('chat:room', args=(room,)))
    return render(request, 'chat/remove_user.html', {'user': user})

chat/templates/chat/add_users.html
{% extends 'chat/base.html' %}

{% block content %}
<div class="container shadow p-3 mt-4 mb-5 bg-white rounded">
    <div class="card-body">
        <form method="POST">
            {% csrf_token %}
            {% for user in users %}
            <div class="form-check">
                <input name="users[]" class="form-check-input" type="checkbox" value="{{user.id}}" id="defaultCheck1">
                <label class="form-check-label" for="defaultCheck1">
                    {{user.user}}
                </label>
            </div>

            {% endfor %}
            <button class="btn btn-success">Add</button>
        </form>
    </div>
</div>

{% endblock %}

chat/templates/chat/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>

    <!-- JQUERY -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

    <!-- FA ICON -->
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>

    <!-- MY CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <span class="navbar-brand mb-0">Chat <i class="fas fa-comments"></i></span>
        <span class="navbar-text">Welcome {{userlist_user.display_name}}</span>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'index' %}">Account Settings</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'chat:index' %}">Users/Groups</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    {% block content %}

    {% endblock %}
</body>

</html>

chat/templates/chat/change.html
{% extends 'chat/base.html' %}

{% block content %}
<div class="container">
    {% if change == 'name' %}
    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label>Change Name</label>
            <input name='name' type="text" class="form-control" placeholder="Enter Name">
        </div>
        <button type="submit" class="mt-2 btn btn-success">Change</button>
    </form>
    {% endif %}
</div>
{% endblock %}

chat/templates/chat/delete_leave.html
{% extends 'chat/base.html' %}

{% block content %}
<div class="container">
    <form method="POST">
        {% csrf_token %}
        {% if status == 'change_name' %}
        <h3 class="lead">Change Group Name</h3>
        <input name='change' class="form-control" type="text">
        {% else %}
        <p class="container alert alert-danger">You want to {{status}} the group?</p>
        {% endif %}
        <button class="mt-2 btn btn-success" type="submit">Confirm</button>
    </form>
</div>
{% endblock %}

chat/templates/chat/index.html
{% extends 'chat/base.html' %}

{% load static %}
{% block content %}

<body id="index">
  <div class="container">
    <div class="shadow p-3 mt-4 mb-5 bg-white rounded">



      <div class="form-group">
        <label>Create a Room</label>
        <input class="form-control" id="room-name-input" type="text" size="100" />
      </div>
      <button class="btn btn-info" onclick="create_room()">Create</button><br />


      <!-- Private Chat -->

      <div class="mt-2 list-group">
        <p class="lead">Users</p>
        {% for user in users %}
        <div class="list-group-item list-group-item-action">
          <a class="btn" href="{% url 'chat:get_id' pk=user.pk %}">{{user.display_name}}
            <!-- Notification -->
            {% for notify in user.notification.all %}
            {% if request.user == notify.receiver and notify.new_message %}
            <small class="badge badge-success">{{notify.count}}</small>
            {% endif %}
            {% endfor %}
          </a>

        </div>
        {% endfor %}
      </div>

      <!-- Groups -->

      <div class="mt-2 list-group">
        <p class="lead">Groups</p>
        {% for room in rooms %}
        <div class="list-group-item list-group-item-action">
          <div class="float-right">
            <button id="dropdownMenu2" data-toggle="dropdown" class="btn"><i class="fa fa-ellipsis-v"></i></button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
              <a href="{% url 'chat:room_rel' pk=room.id %}?leave_room" class="dropdown-item">Leave Group</a>
              {% if room.room.admin.username == request.user.username %}
              <div class="dropdown-divider"></div>
              <a href="{% url 'chat:room_rel' pk=room.id %}?change_name" class="dropdown-item">Change Name</a>
              <a href="{% url 'chat:room_rel' pk=room.id %}?delete_room" class="dropdown-item">Delete Group</a>
              <a href="{% url 'chat:add_users' pk=room.room.id %}" class="dropdown-item">Add Users</a>
              {% endif %}
            </div>
          </div>
          <button class="btn" value="{{room.room.room_id}}" onclick="getroom()">{{room.room}}
            <!-- Notification -->
            {% for notify in room.room.notification.all %}
            {% if request.user == notify.user and notify.new_message %}
            <small class="badge badge-success">{{notify.count}}</small>
            {% endif %}
            {% endfor %}
          </button>
        </div>
        {% endfor %}
      </div>

    </div>
  </div>
</body>
<script>
  document.querySelector("#room-name-input").focus();
  document.querySelector("#room-name-input").onkeyup = function (e) {
    if (e.keyCode === 13) {
      // enter, return
      create_room()
      document.querySelector("#room-name-submit").click();
    }
  };

  function create_room() {
    room = document.querySelector("#room-name-input").value
    if (room.trim() != '') {
      $.ajax({
        type: 'POST',
        url: "{% url 'chat:create_room' %}",
        data: {
          'room': room,

        },
        success: function (data) {
          console.log(data.room)
          window.location.pathname = "/chat/chat-room/" + data.room + "/";
          console.log('submitted')
        }
      })
    }
  }

  function getroom(e) {
    var roomid = window.event.srcElement.value
    var roomname = window.event.srcElement.textContent
    $.ajax({
      type: 'POST',
      url: "{% url 'chat:room_id' %}",
      data: {
        'room': roomid,
        'room_name': roomname,
      },
      success: function () {
        window.location.pathname = "/chat/chat-room/" + roomid + "/";
        console.log('submitted')
      }
    })
  }

  function room_id() {
    room = document.querySelector("#room-name-input").value
    $.ajax({
      type: 'POST',
      url: "{% url 'chat:room_id' %}",
      data: {
        'room': room
      },
      success: function () {
        window.location.pathname = "/chat/chat-room/" + room + "/";
        console.log('submitted')
      }
    })
  }



  document.querySelector("#room-name-submit").onclick = function (e) {
    var roomName = document.querySelector("#room-name-input").value;
    window.location.pathname = "/chat/" + roomName + "/";
  };
</script>
{% endblock %}

chat/templates/chat/remove_user.html
{% extends 'chat/base.html' %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    <div class="container">
        <p class="container alert alert-danger">You want to remove {{user.user}} from the group?</p>
        <button class="btn btn-success" type="submit">Confirm</button>
    </div>
</form>
{% endblock %}

chat/templates/chat/room.html
{% extends 'chat/base.html' %}
{% block content %}

<div class="container shadow p-3 mt-4 mb-5 bg-white rounded">
  <div>
    {% if group == 'room' %}
    <button type="button" data-toggle="modal" data-target="#exampleModal" class="btn float-right">
      <i style="font-size:24px" class="fa fa-info-circle" aria-hidden="true"></i>
    </button>
    {% endif %}
    <h2> {{chat_name}} </h2>
  </div>

  <hr>
  <div class="conversation" id="chat-log"></div>
  <br />
  <div class="form-group">
    <input width="50%" class="form-control" id="chat-message-input" type="text" size="50" />
    <input class="btn mt-2 btn-info" id="chat-message-submit" type="button" value="Send" />
  </div>

  <!-- Group Display's -->
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Group Details</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p class="lead">Group Members</p>

          <div>
            {% for user in users %}
            <p>
              {% if user.room.admin == user.user %}
              {{user.user}} <span class="text-success">Admin</span>
              {% else %}
              {% if admin %}
              <a href="{% url 'chat:remove' user.id %}" class="float-right btn btn-link">Remove</a>
              {{user.user}}
              {% else %}
              {{user.user}}
              {% endif %}
              {% endif %}
            </p>
            {% endfor %}

          </div>
          <hr>
          {% if admin %}
          <a href="{% url 'chat:add_users' pk=roomId %}" class="btn btn-sm btn-outline-primary">Add Users</a>
          {% endif %}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>


  {{ room_id|json_script:"room-id" }}
</div>
<script>
  var user = "{{request.user.username}}"
  //const user = document.querySelector("#user").innerHTML;
  const roomId = JSON.parse(
    document.getElementById("room-id").textContent
  );

  const chatSocket = new WebSocket(
    "ws://" + window.location.host + "/ws/chat/chat-room/" + roomId + "/"
  );

  chatSocket.onmessage = function (e) {
    const data = JSON.parse(e.data);
    if (data.label == 'private') {
      if (data.state == "fetched_messages" && user == data.user) {
        data.messages.map((message) => {
          user == message.user
            ? (document.querySelector(
              "#chat-log"
            ).innerHTML += `<div class="my_mess"><time class="m-0 small float-right">${message.time}.</time>${message.content}</div>`)
            : (document.querySelector(
              "#chat-log"
            ).innerHTML += `<div class="received"><time class="m-0 small float-right">${message.time}.</time>${message.content}</div>`);
        });
      } else {
        user == data.user
          ? (document.querySelector(
            "#chat-log"
          ).innerHTML += `<div class="my_mess"> <time class="m-0 small float-right">${data.time}</time> ${data.message}</div>`)
          : (document.querySelector(
            "#chat-log"
          ).innerHTML += `<div class="received"><time class="m-0 small float-right">${data.time}</time>${data.message}</div>`);
      }
    }
    else {
      if (data.state == "fetched_messages" && user == data.user) {
        data.messages.map((message) => {
          user == message.user
            ? (document.querySelector(
              "#chat-log"
            ).innerHTML += `<div class="my_mess"><time class="m-0 small float-right">${message.time}.</time><small class='text-danger'>${message.user}: </small>${message.content}</div>`)
            : (document.querySelector(
              "#chat-log"
            ).innerHTML += `<div class="received"><time class="m-0 small float-right">${message.time}.</time><small class='text-danger'>${message.user}: </small>${message.content}</div>`);
        });
      } else {
        user == data.user
          ? (document.querySelector(
            "#chat-log"
          ).innerHTML += `<div class="my_mess"><time class="m-0 small float-right">${data.time}.</time><small class='text-danger'>${data.user}: </small>${data.message}</div>`)
          : (document.querySelector(
            "#chat-log"
          ).innerHTML += `< div="received"><time class="m-0 small float-right">${data.time}.</time><small class='text-danger'>${data.user}: </small>${data.message}</>`);
      }
    }
    document.getElementById('chat-log').lastChild.scrollIntoView(false);
  };

  chatSocket.onclose = function (e) {
    console.error("Chat socket closed unexpectedly");
  };

  document.querySelector("#chat-message-input").focus();
  document.querySelector("#chat-message-input").onkeyup = function (e) {
    if (e.keyCode === 13) {
      // enter, return
      console.log();
      document.querySelector("#chat-message-submit").click();
    }
  };

  setTimeout(() => {
    console.log(roomId)
    chatSocket.send(
      JSON.stringify({
        command: "fetch messages",
        chat_id: roomId,
        user: user,
      })
    );
  }, 500);

  document.querySelector("#chat-message-submit").onclick = function (e) {
    const messageInputDom = document.querySelector("#chat-message-input");
    const message = messageInputDom.value;
    if (message.trim() != '') {
      chatSocket.send(
        JSON.stringify({
          command: "new message",
          message: message,
          user: user,
          chat_id: roomId,
        })
      )
    }
    messageInputDom.value = "";
  };
</script>
{% endblock %}