chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.index, name='index'),
    path('chat-room/<str:room_name>/', views.room, name='room'),
    path('room/', views.room_id, name='room_id'),
    path('<int:pk>/', views.get_id, name='get_id'),
    path('create_room/', views.create_room, name='create_room'),
    path('addusers/<int:pk>/', views.add_users, name='add_users'),
    path('room/<int:pk>/', views.room_rel, name='room_rel'),
    path('change-setting/', views.changeSettings, name='change'),
    path('remove-user/<int:pk>/', views.remove_user, name='remove'),
]

login/urls.py
from . import views
from django.urls import path

app_name = 'login'

urlpatterns = [
    path('', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
]

mysite/urls.py
from django.conf.urls import include
from django.urls import path
from django.contrib import admin
from login.views import user_login, user_logout, register, index


urlpatterns = [
    path('', index, name='index'),
    path('chat/', include('chat.urls')),
    path('admin/', admin.site.urls),
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('register/', register, name='register'),
]

login/models.py
from django.db import models

# Create your models here.

login/forms.py
from django import forms
from django.core import validators
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

login/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from .forms import UserForm
from chat.models import UserList


def index(request):
    return render(request, 'login/index.html')


def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)

        if user_form.is_valid():
            username = user_form.save()
            username.set_password(username.password)
            username.save()

            # EXTRA

            user = User.objects.get(username=username.username)
            new_user = UserList(user=user, display_name=username.username)
            new_user.save()

            # TILL HERE
            registered = True
            login(request, user)
            return HttpResponseRedirect('/chat/')
        else:
            print(user_form.errors)
            return render(request, 'login/register.html', {'registered': registered, 'user_form': user_form})
    else:
        user_form = UserForm()
        return render(request, 'login/register.html', {'registered': registered, 'user_form': user_form})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('pass')

        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse('Acc not active')

        else:
            print("Someone tries to login and failed")
            return HttpResponse('invalid login details')

    else:
        return render(request, 'login/login.html', {})

login/templates/login/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <!-- CSS only -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

  <!-- JS, Popper.js, and jQuery -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
    integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
    crossorigin="anonymous"></script>
  <title>Document</title>
</head>

<body>
  {% block body %}
  {% endblock%}
</body>

</html>

login/templates/login/index.html
{% extends "login/base.html" %}

{% block body %}
<title>Index</title>
<div class="container">
    <div class="jumbotron">
        <h2><a href="{% url 'chat:index' %}">Chat </a><i class="fas fa-comments"></i></h2>
        {% if user.is_authenticated %}
        <a href="{% url 'logout' %}" class="btn btn-outline-warning">Logout</a>
        <br>
        <a href="{% url 'chat:change' %}?name" class="mt-2 btn btn-primary">Change Username</a>
        {% else %}
        <a href="{% url 'login' %}" class="btn btn-outline-success">Login</a>
        <a href="{% url 'register' %}" class="btn btn-outline-success">Register</a>
        {% endif %}
    </div>
</div>
{% endblock %}

login/templates/login/login.html
{% extends "login/base.html" %}

{% block body %}
<title>Login</title>
<div class="container">
    <h1>Please login</h1>
    <form method="POST" action="{% url 'login' %}">
        {% csrf_token %}


        <div class="form-group">
            <label for="username">Username: </label>
            <input type="text" placeholder="Username" class="form-control" name="username" aria-describedby="emailHelp">
        </div>
        <div class="form-group">
            <label for="pass">Password</label>
            <input type="password" class="form-control" name="pass">
        </div>

        <button type="submit" class="btn btn-primary">Login</button>

        <small class="form-text text-muted">
            <a href="{% url 'register' %}">Already registered?</a>
        </small>


    </form>
</div>

{% endblock %}

login/templates/login/register.html
{% extends "login/base.html" %}

{% load crispy_forms_tags %}

{% block body %}

<title>Register</title>
{% if registered %}
<h2>Thanks For registering</h2>
{% else %}
<h2>Registration Form:</h2>
<div class="container">
  <div style="width: 50%;">
    <form method="POST" class="form-group">
      {% csrf_token %}
      {{user_form|crispy}}
      <input type="submit" value="Submit" />
    </form>
  </div>
</div>

<h2>
  {{error}}
</h2>
{% endif %} {% endblock %}